FROM python:3.11.6
WORKDIR /app
#COPY ./requirements.txt /app
#RUN pip install -r requirements.txt
RUN pip install flask
COPY . .
EXPOSE 80
#ENV FLASK_APP=app.py
#CMD ["flask", "run", "--host", "0.0.0.0"]
ENTRYPOINT python app.py
