apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  selector:
    matchLabels:
      app: java
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
      - name: java
        image: sailesh94/java:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java
  name: java-nodeport
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java
  type: NodePort